[package]
name = "mirrord-http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
tracing.workspace = true
futures.workspace = true

hyper = { version = "1.0.0-rc.1", features = ["full"] }
tokio = { version = "*", features = ["full"] }
httparse = "1"
fancy-regex = { version = "0.10" }

[dev-dependencies]
rstest = "*"